version: '3'
services:
  reservations:
    build:
      context: ./
      dockerfile: Dockerfile.prod.makerspace
    env_file:
      - .env
    volumes:
      - ./public:/usr/src/app/public
      - /tmp/reservations-unicorn:/tmp/unicorn
