version: '3'
services:
  reservations:
    build:
      context: ./
      dockerfile: Dockerfile.prod.makerspace
    env_file:
      - .env
    restart: always
    volumes:
      - ./public:/usr/src/app/public
      - /tmp/cobotmakerspace-equipment:/tmp/unicorn
      - ${RES_DB_SOCKET}:${RES_DB_SOCKET}
